### ISSUE TITLE
local_settings from ENV

### ISSUE THREAD

**Issue by jareware** [hopsoft/docker-graphite-statsd#44]
Would be really handy if you could provide config overrides in `/opt/graphite/webapp/graphite/local_settings.py` through the environment as well, would go nicely in `docker-compose.yml` for instance.

**Comment by hopsoft** [comment]
Nice suggestion. Thanks.

**Comment by jareware** [comment]
A more concrete example, this would be really nice:

```
graphite:
  image: hopsoft/graphite-statsd
  environment:
    - TIME_ZONE=Europe/Helsinki
```

Instead of my current:

```
graphite:
  image: hopsoft/graphite-statsd
  volumes:
    - ./local_settings.py:/opt/graphite/webapp/graphite/local_settings.py
```

Because I'd imagine a majority of users need to set at least `TIME_ZONE` to get sensible timestamps on their UI. :)
