### ISSUE TITLE
Unable to receive any stats.

### ISSUE THREAD

**Issue by danhanly** [hopsoft/docker-graphite-statsd#64]
I'm using `docker-compose` to build this, here's my config:

```
  graphite-statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "5000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
```

I'm able to access the graphite interface at `http://localhost:5000` however, using the test command in the readme, I'm unable to send any stats to graphite.

If I run `echo "stats" | nc localhost 8126` then I don't see my stats anywhere.

Is there a step I'm not seeing in the Readme to getting this up and running?
