### ISSUE TITLE
port 8125 on localhost

### ISSUE THREAD

**Issue by vcraescu** [hopsoft/docker-graphite-statsd#75]
Hi

For some reason port 8125 it's not opened on the host.

```
  graphite:
    container_name: graphite
    image: hopsoft/graphite-statsd
    ports:
      - "8080:80"
      - "8125:8125/udp"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8126:8126"
```

All the other ports are exposed on the host except 8125.
